#!/bin/sh

if [ "$#" -lt 4 ]; then
  usage; exit 1
fi

STP_PATH=$(dirname $0)

# option: +
user_id=$1; name=$2; bundle_id=$3; dest=$4;
# option: *
display_name="$name"
extension_name="$name"Pack
extension_bundle_id="$bundle_id.pack"
# default options
src=$(pwd)
dest_app_relative_path="app"
# perf options
export_gif_mp4=;
# fastlane
fastfile_path="./fastlane/Fastfile"
filefile_init_flag="#Fastfile@gostp-init-flag"
filefile_created_flag="#Fastfile@gostp-created-flag"

#set args
while test $# -gt 0
do
  local option="$1"
  case "$option" in
    -s|--source-path)
      src=$2
      ;;
    -a|--app-relative-path)
      dest_app_relative_path=$2
      ;;
    -n|--display-name)
      display_name=$2
      ;;
    -e|--extension-name)
      extension_name=$2
      ;;
    -b|--extension-bundle-id)
      extension_bundle_id=$2
      ;;
    --export-gif-mp4)
      export_gif_mp4=1
      ;;
  esac
  shift
done
