#!/bin/sh

python $STP_PATH/build.py "$src" "$dest" \
--name "$name" \
--display-name "$display_name" \
--bundle-id "$bundle_id" \
--extension-name "$extension_name" \
--extension-bundle-id "$extension_bundle_id" \
--dest-relative-path "$dest_app_path"

build_result=$?
if [ $build_result -ne 0 ]; then
  echo "[!] Error when building: $dest"
  exit $build_result
fi
cd "$dest"

if [ $export_gif_mp4 -eq 1 ]; then
  #create gif
  echo "[i] Creating gifs from pngs ... $dest/gif"
  find . -maxdepth 1 -type f -name '*.png' | \
  while read FILE; do
    FILENAME="${FILE%.*}";
    apng2gif "$FILE" && mkdir gif;
    mv -f "$FILENAME".gif gif/;
    echo gif/"$FILENAME".gif;
  done &>/dev/null;

  #create mp4 from gifs
  echo "[i] Creating mp4 videos from gifs ... $dest/video"
  mkdir -p video; find gif -maxdepth 1 -type f -iname "*.gif" | \
  while read FILE; do
    FILENAME=$(basename ${FILE%.*});
    ffmpeg -stream_loop 5 -r 5 -i gif/$FILENAME.gif -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video/$FILENAME.mp4 -y;
    echo video/$FILENAME.mp4;
  done &>/dev/null;
fi
