#!/bin/sh
source $(dirname $0)/_gostp-define
source $(dirname $0)/_gostp-build

#start setup app config ...
echo "[i] Staring xcode project configuration ..."
cd "$dest/$dest_app_relative_path"

fastlane init -u $user_id

if ! grep -qE "$filefile_init_flag" $fastfile_path
then
  fastfile_content=$(cat "$fastfile_path")
  cat >$fastfile_path <<EOF
$filefile_init_flag
produce(username:"$user_id", app_name:"$name", app_identifier:"$bundle_id", skip_itc:true)
produce(username:"$user_id", app_name:"$extension_name", app_identifier:"$extension_bundle_id", skip_itc:true)
sigh(app_identifier:"$bundle_id")
sigh(app_identifier:"$extension_bundle_id")
update_project_provisioning(xcodeproj:"$name.xcodeproj",profile: "./AppStore_$bundle_id.mobileprovision", target_filter:"$name")
update_project_provisioning(xcodeproj:"$name.xcodeproj",profile: "./AppStore_$extension_bundle_id.mobileprovision", target_filter:"StickerPackExtension")
${fastfile_content}
EOF
fi

fastlane release

#insert finshed flag
if ! grep -qE "$filefile_created_flag" $fastfile_path
then
  echo $filefile_created_flag >> $fastfile_path
fi

echo "$dest"

# if [ ! -f $fastfile_path ]; then
# fi
