#!/bin/sh
source $(dirname $0)/_gostp-define
source $(dirname $0)/_gostp-build

#start setup app config ...
echo "[i] Staring to upload updated project ..."
cd "$dest_app_path"

if ! grep -qE "$fastfile_init_flag" $fastfile_path
then
  echo "[!] This project has not been initialized. Complete '$ gostp create' first. "
  exit 1
fi

#insert finshed flag
echo $(grep -qE "$fastfile_created_flag" $fastfile_path)
if ! grep -qE "$fastfile_created_flag" $fastfile_path
then
  echo "[!] This project has not been initialized. Complete '$ gostp create' first. "
  exit 1
fi

git xcp beta StickerPackExtension
fastlane gym --scheme StickerPackExtension && fastlane deliver -f

if [ $? -eq 0 ]; then
  echo "$dest"
else
  echo "[!] Something wroing while build and upload binary!"
  exit 1
fi
