#!/bin/sh
source $(dirname $0)/_gostp-define
source $(dirname $0)/_gostp-build

#start setup app config ...
echo "[i] Staring to upload updated project ..."
cd "$dest_app_path"

if ! grep -qE "$fastfile_init_flag" $fastfile_path
then
  echo "[!] This project has not been initialized. Complete '$ gostp create' first. "
  exit 1
fi

#insert finshed flag
echo $(grep -qE "$fastfile_created_flag" $fastfile_path)
if ! grep -qE "$fastfile_created_flag" $fastfile_path
then
  echo "[!] This project has not been initialized. Complete '$ gostp create' first. "
  exit 1
fi

#git xcp beta
if [ $skip_git_actions -eq 0 ]; then
  git xcp beta "$extension_name" && git xcp beta $name
fi

fastlane gym --scheme "$extension_name" && fastlane deliver -f

if [ $? -eq 0 ]; then

  if [ $skip_git_actions -eq 0 ]; then
    cd $dest
    git add . && git commit -m "[Updated - $name]"
    cd -
  fi

  echo "$dest"
else
  echo "[!] Something wrong while build and upload binary!"

  if [ $skip_git_actions -eq 0 ]; then
    cd $dest_app_path
    echo "[i] Reverting build vertions ..."
    git xcp beta "$extension_name" --revert && git xcp beta $name --revert
    cd -
  fi

  exit 1
fi
