#!/usr/bin/env sh

usage()
{
  printf "Usage: "
	printf "\n"
	printf "%s [-v|--version] [-h|--help] <command> [option ...]\n" "$(basename $0)"
	printf "\n"
	printf "Commands:"
	printf "\n"
	printf "[create | update | build] <account> <app/project name> <bundle id> <destination path>"
	printf "\t%s\n" "-s,--source-path: Source path of sticker assets "
	printf "\t%s\n" "-a,--app-relative-path: Destination App Relative path"
	printf "\t%s\n" "-n,--display-name: App Display Name"
	printf "\t%s\n" "-i,--itc-display-name: Appstore/iTC Display Name"
	printf "\t%s\n" "-e,--extension-name: App Extension Name"
	printf "\t%s\n" "-b,--extension-bundle-id: App Extension Bundle Id"
  printf "\t%s\n" "--skip-export-gif-mp4: Skip to convert and export with gif, mp4 from stickers"
  printf "\t%s\n" "--skip-git-actions: Skip all the git integrations"
}

version() {
	echo "0.1"
}

main() {
	if [ "$#" -lt 1 ]; then
		usage; exit 1
	fi

	local subcommand="$1"; shift
	case $subcommand in
		"-h"|"--help")
			usage; exit 0
			;;
		"-v"|"--version")
			version; exit 0
			;;
	esac

	local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
	if [ ! -e "$workingdir/gostp-$subcommand" ]; then
		usage; exit 1
	fi

	source "$workingdir/gostp-$subcommand" "$@"
}
main "$@"
