#!/usr/bin/env sh

usage()
{
  printf "Usage: "
	printf "\n"
	printf "%s [-v|--version] [-h|--help] <command> [option ...]\n" "$(basename $0)"
	printf "\n"
	printf "Commands:"
	printf "\n"
	printf "new <account> <app/project name> <bundle id> <destination path>"
	printf "\t%s\n" "-s,--source-path: Prints version"
	printf "\t%s\n" "-a,--app-relative-path: Prints version"
	printf "\t%s\n" "-n,--display-name: Prints version"
	printf "\t%s\n" "-e,--extension-name: Prints version"
	printf "\t%s\n" "-b,--extension-bundle-id: Prints version"
}

version() {
	echo "0.1"
}

main() {
	if [ "$#" -lt 1 ]; then
		usage; exit 1
	fi

	local subcommand="$1"; shift
	case $subcommand in
		"-h"|"--help")
			usage; exit 0
			;;
		"-v"|"--version")
			version; exit 0
			;;
	esac

	local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
	if [ ! -e "$workingdir/gostp-$subcommand" ]; then
		usage; exit 1
	fi

	source "$workingdir/gostp-$subcommand" "$@"
}
main "$@"
